"""
Research Gap Detector

This module analyzes multiple academic papers using the Gemini model to identify
common themes, shared limitations, overlooked research directions (gaps), and
propose novel research project ideas based on those gaps.
"""

import os
import logging
from dotenv import load_dotenv
from typing import Any
from google import genai
from google.genai import types

from backend.gap_prompt import create_gap_prompt

load_dotenv()

logger = logging.getLogger(__name__)


def detect_research_gap(papers: list[dict[str, Any]]) -> str:
    """
    Analyzes multiple research papers to identify limitations and unexplored gaps.

    Args:
        papers (list of dict): A list of dictionaries representing the uploaded papers.
            Each dictionary should contain 'name' and 'text'.

    Returns:
        str: A Markdown formatted summary of research gaps and novel ideas generated by Gemini.
    """

    if len(papers) < 2:
        logger.warning("Attempted gap detection with less than 2 papers.")
        return "Please upload at least two research papers."

    logger.info(f"Generating gap detection prompt for {len(papers)} papers.")
    prompt = create_gap_prompt(papers)

    try:
        logger.info("Sending gap detection request to Gemini API.")
        client = genai.Client()
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.2,
                max_output_tokens=4096,
            ),
        )
        logger.info("Successfully received gap detection response from Gemini API.")
        return response.text
    except Exception as e:
        logger.error(f"Gemini API error during gap detection: {e}", exc_info=True)
        raise e